name: Huntandgatherings
favicon: null
layout_spectrum: 0.2041272281203419
typography_spectrum: 0.0009264489635825157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7863508521113545
  lightness: 0.9086739788763225
  saturation: 0.1796587468124926
  rhythmicContrast: 0.125400546239689
purpose: []
